name: go_blog
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  #State Management
  get: ^4.6.5

  #http client
  dio: ^4.0.6
  html: ^0.15.0

  #html to widget
  flutter_html: ^2.2.1

  #database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #generating
  build_runner: ^2.2.0
  hive_generator: ^1.1.3

  #launch url
  url_launcher: ^6.1.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/img/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
